title: Michele Schimd - ITIS Zuccante
author: Michele Schimd
email: michele.schimd@itiszuccante.edu.it
description: >- # this means to ignore newlines until "baseurl:"
  Materiale di studio e di esercizio per gli alunni dell'ITIS Carlo
  Zuccante di Venezia-Mestre.
baseurl: "" 
url: https://profschimd.github.io/
domain: profschimd.github.io
prevent_indexing: false

minima:
  # generate social links in the footer
  social_links:
    github:  ProfSchimd
    linkedin: michele-schimd-44a85160


collections:
  materie:
    output: true
  classi:
    output: true

header_pages:
  - content/dispense.md

# Build settings
# plugins:
#   - jekyll-feed

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
