baseURL = 'https://profschimd.github.io/'
canonifyURLs = true
languageCode = 'en-us'
title = 'Michele Schimd'
theme = 'skihugo'
[params]
  author = 'Michele Schimd'
  description = 'Materiale di studio e di esercizio per gli alunni dello Zuccante.'
[params.social]
    mail = 'michele.schimd@itiszuccante.edu.it'
    github = 'ProfSchimd'
    linkedin = 'michele-schimd-44a85160'
    stackoverflow = '18081937'

[markup]
  [markup.goldmark.renderer]
    unsafe=true
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    noClasses=false
    
[menu]
[[menu.main]]
  identifier = 'materie'
  name = 'Materie'
  description = 'Lista materie'
  url = '/materie/'
  weight = -90
[[menu.main]]
  identifier = 'about'
  name = ''
  pre = '<i class="bi bi-info-circle"></i>'
  description = 'Informazioni sul sito'
  url = '/about/'
  weight = -50

